project_id = "epvarnbcturugkecsgkx"

[functions.create-checkout-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.get-download-link]
verify_jwt = false

[functions.scan-receipt]
verify_jwt = false
